//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaToDo.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABDEntities : DbContext
    {
        public ABDEntities()
            : base("name=ABDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorii> Categoriis { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Tip_Task> Tip_Task { get; set; }
        public virtual DbSet<Tip_Utilizator> Tip_Utilizator { get; set; }
        public virtual DbSet<Utilizatori> Utilizatoris { get; set; }
    }
}
