//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaToDo.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Task
    {
        public Task()
        {
        }

        public Task(int iDTipTask, int iDCategorie, int iDUtilizator, string titlu, string descriere, DateTime deadline, bool stare, bool remainder)
        {
            IDTipTask = iDTipTask;
            IDCategorie = iDCategorie;
            IDUtilizator = iDUtilizator;
            Titlu = titlu;
            Descriere = descriere;
            Deadline = deadline;
            Stare = stare;
            Remainder = remainder;
        }

        public int IDTask { get; set; }
        public int IDTipTask { get; set; }
        public int IDCategorie { get; set; }
        public int IDUtilizator { get; set; }
        public string Titlu { get; set; }
        public string Descriere { get; set; }
        public System.DateTime Deadline { get; set; }
        public bool Stare { get; set; }
        public bool Remainder { get; set; }

        public virtual Categorii Categorii { get; set; }
        public virtual Tip_Task Tip_Task { get; set; }
        public virtual Utilizatori Utilizatori { get; set; }
    }
}
