//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaToDo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizatori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilizatori()
        {
            this.Categoriis = new HashSet<Categorii>();
            this.Tasks = new HashSet<Task>();
        }

        public Utilizatori(int IdTipUtilizator, string name, string secondName, string username, string password, string email)
        {
            IDTip_Utilizator = IdTipUtilizator;
            Nume = name;
            Prenume = secondName;
            Username = username;
            Pass = password;
            E_mail = email;
        }


        public int IDUtilizator { get; set; }
        public int IDTip_Utilizator { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string Username { get; set; }
        public string Pass { get; set; }
        public string E_mail { get; set; }
        public byte[] Poza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categorii> Categoriis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual Tip_Utilizator Tip_Utilizator { get; set; }
    }
}
